# Base YAML config for the Vindriktning add-on board
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_sensors

uart:
  rx_pin: GPIO12
  baud_rate: 9600
  id: bus_softuart

sensor:
  - platform: pm1006
    pm_2_5:
      name: "PM2.5"
    uart_id: bus_softuart

  - platform: bme280
    temperature:
      name: "temperature"
      oversampling: 16x
    pressure:
      name: "pressure"
    humidity:
      name: "humidity"
    address: 0x76
    update_interval: 60s
    
  - platform: sgp30
    eco2:
      name: "eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "TVOC"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 1s

light:
  - platform: status_led
    id: status_indicator
    pin: GPIO14
